"""
PDF Report Generator for Kundli and Marriage Matching
"""
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm, cm
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, Table,
                                  TableStyle, HRFlowable, PageBreak)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.pdfgen import canvas
from reportlab.graphics.shapes import Drawing, Rect, String, Line, Polygon
from reportlab.graphics import renderPDF
import io, math

# Colors
GOLD = colors.HexColor("#C8960C")
DARK_RED = colors.HexColor("#8B0000")
SAFFRON = colors.HexColor("#FF6600")
CREAM = colors.HexColor("#FFF8E7")
LIGHT_GOLD = colors.HexColor("#FDF3DC")
MAROON = colors.HexColor("#800000")
GREEN = colors.HexColor("#2E7D32")
BLUE_DARK = colors.HexColor("#1A237E")
GRAY_LIGHT = colors.HexColor("#F5F5F5")

def make_styles():
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle("Title1", fontName="Helvetica-Bold", fontSize=22,
        textColor=DARK_RED, alignment=TA_CENTER, spaceAfter=6))
    styles.add(ParagraphStyle("Title2", fontName="Helvetica-Bold", fontSize=16,
        textColor=MAROON, alignment=TA_CENTER, spaceAfter=4))
    styles.add(ParagraphStyle("SectionHead", fontName="Helvetica-Bold", fontSize=13,
        textColor=DARK_RED, spaceBefore=10, spaceAfter=4,
        borderPad=4, backColor=LIGHT_GOLD))
    styles.add(ParagraphStyle("Normal1", fontName="Helvetica", fontSize=10,
        textColor=colors.black, spaceAfter=3))
    styles.add(ParagraphStyle("Small", fontName="Helvetica", fontSize=8,
        textColor=colors.grey))
    styles.add(ParagraphStyle("Center", fontName="Helvetica", fontSize=10,
        alignment=TA_CENTER))
    styles.add(ParagraphStyle("Bold1", fontName="Helvetica-Bold", fontSize=10,
        textColor=MAROON))
    styles.add(ParagraphStyle("Sanskrit", fontName="Helvetica-BoldOblique", fontSize=11,
        textColor=DARK_RED, alignment=TA_CENTER, spaceAfter=2))
    return styles

def header_footer(canvas_obj, doc):
    canvas_obj.saveState()
    w, h = A4
    canvas_obj.setFillColor(DARK_RED)
    canvas_obj.rect(0, h-18*mm, w, 18*mm, fill=1, stroke=0)
    canvas_obj.setFillColor(colors.white)
    canvas_obj.setFont("Helvetica-Bold", 11)
    canvas_obj.drawCentredString(w/2, h-12*mm, "Jyotish Kundli System  |  Vedic Astrology Report")
    canvas_obj.setFillColor(SAFFRON)
    canvas_obj.rect(0, h-21*mm, w, 3*mm, fill=1, stroke=0)
    # Footer
    canvas_obj.setFillColor(CREAM)
    canvas_obj.rect(0, 0, w, 12*mm, fill=1, stroke=0)
    canvas_obj.setFillColor(DARK_RED)
    canvas_obj.setFont("Helvetica", 8)
    canvas_obj.drawString(15*mm, 4*mm, "Generated by Jyotish Kundli System")
    canvas_obj.drawRightString(w-15*mm, 4*mm, f"Page {doc.page}")
    canvas_obj.restoreState()

def north_indian_chart_svg(houses, planets, size=280):
    """Draw North Indian style Kundli chart as ReportLab Drawing."""
    d = Drawing(size, size)
    s = size
    c = s / 2
    # Outer rect
    d.add(Rect(0, 0, s, s, fillColor=LIGHT_GOLD, strokeColor=DARK_RED, strokeWidth=2))
    # Inner diamond
    pts = [c,s-5, s-5,c, c,5, 5,c]
    d.add(Polygon(pts, fillColor=CREAM, strokeColor=DARK_RED, strokeWidth=1.5))
    # Diagonal lines
    d.add(Line(0,0, s,s, strokeColor=DARK_RED, strokeWidth=1))
    d.add(Line(s,0, 0,s, strokeColor=DARK_RED, strokeWidth=1))
    d.add(Line(0,0, c,c, strokeColor=DARK_RED, strokeWidth=1))

    # House positions (North Indian) - center of each cell (approx)
    # House labels in North Indian: Lagna always top-center
    # Positions for 12 houses in North Indian format
    house_centers = [
        (c, s*0.82),      # H1 top-center (Lagna)
        (s*0.18, s*0.82), # H2
        (s*0.1, c),       # H3
        (s*0.18, s*0.18), # H4
        (c, s*0.18),      # H5
        (s*0.82, s*0.18), # H6
        (s*0.9, c),       # H7
        (s*0.82, s*0.82), # H8
        (c, s*0.82),      # Actually this needs adjustment
        (s*0.35, s*0.55), # H9 inner
        (c, s*0.55),      # H10
        (s*0.65, s*0.55), # H11
    ]
    # Simplified - place house numbers
    north_positions = [
        (c, s*0.88), (s*0.12, s*0.88), (s*0.05, c),
        (s*0.12, s*0.12), (c, s*0.12), (s*0.88, s*0.12),
        (s*0.95, c), (s*0.88, s*0.88),
        (s*0.72, c), (c, s*0.72), (s*0.28, c), (c, s*0.28)
    ]

    # Build house->planet mapping
    house_planets = {i+1: [] for i in range(12)}
    for pname, pdata in planets.items():
        h = pdata.get("house", 1)
        short = pname[:3]
        house_planets[h].append(short)

    for i, (hx, hy) in enumerate(north_positions):
        h_num = i + 1
        house_rashi = houses[i]
        # House number
        d.add(String(hx, hy+8, str(house_rashi+1),
            fontName="Helvetica-Bold", fontSize=9, fillColor=DARK_RED,
            textAnchor="middle"))
        # Planet names
        plist = house_planets.get(h_num, [])
        for j, pn in enumerate(plist[:3]):
            d.add(String(hx, hy - j*9, pn,
                fontName="Helvetica", fontSize=7, fillColor=BLUE_DARK,
                textAnchor="middle"))
    # Lagna marker
    d.add(String(c, s*0.88+16, "Lag",
        fontName="Helvetica-Bold", fontSize=8, fillColor=SAFFRON,
        textAnchor="middle"))
    return d

def make_info_table(data_pairs, styles):
    rows = []
    for i in range(0, len(data_pairs), 2):
        row = [
            Paragraph(f"<b>{data_pairs[i][0]}</b>", styles["Normal1"]),
            Paragraph(str(data_pairs[i][1]), styles["Normal1"]),
        ]
        if i+1 < len(data_pairs):
            row += [
                Paragraph(f"<b>{data_pairs[i+1][0]}</b>", styles["Normal1"]),
                Paragraph(str(data_pairs[i+1][1]), styles["Normal1"]),
            ]
        else:
            row += [Paragraph("","Normal1"), Paragraph("","Normal1")]
        rows.append(row)
    t = Table(rows, colWidths=[45*mm, 55*mm, 45*mm, 45*mm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,-1), LIGHT_GOLD),
        ("ROWBACKGROUNDS", (0,0), (-1,-1), [LIGHT_GOLD, CREAM]),
        ("GRID", (0,0), (-1,-1), 0.5, GOLD),
        ("FONTNAME", (0,0), (-1,-1), "Helvetica"),
        ("FONTSIZE", (0,0), (-1,-1), 9),
        ("TOPPADDING", (0,0), (-1,-1), 4),
        ("BOTTOMPADDING", (0,0), (-1,-1), 4),
    ]))
    return t

def planet_table(planets, styles):
    headers = ["Planet", "Rashi", "Degree", "Nakshatra", "Pada", "House", "Lord"]
    rows = [headers]
    for p in ["Sun","Moon","Mars","Mercury","Jupiter","Venus","Saturn","Rahu","Ketu"]:
        d = planets[p]
        rows.append([p, d["rashi"].split("(")[1].rstrip(")"),
                     f"{d['degree']:.2f}°", d["nakshatra"],
                     str(d["pada"]), str(d["house"]), d["lord"]])
    t = Table(rows, colWidths=[25*mm,22*mm,20*mm,32*mm,14*mm,16*mm,22*mm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,0), DARK_RED),
        ("TEXTCOLOR", (0,0), (-1,0), colors.white),
        ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
        ("FONTSIZE", (0,0), (-1,-1), 9),
        ("ROWBACKGROUNDS", (0,1), (-1,-1), [CREAM, LIGHT_GOLD]),
        ("GRID", (0,0), (-1,-1), 0.5, GOLD),
        ("TOPPADDING", (0,0), (-1,-1), 3),
        ("BOTTOMPADDING", (0,0), (-1,-1), 3),
    ]))
    return t

def dasha_table(dashas, styles):
    headers = ["Dasha Lord", "Start Date", "End Date", "Duration (yrs)"]
    rows = [headers]
    for d in dashas[:9]:
        rows.append([d["lord"], d["start"], d["end"], str(d["years"])])
    t = Table(rows, colWidths=[40*mm, 40*mm, 40*mm, 35*mm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,0), MAROON),
        ("TEXTCOLOR", (0,0), (-1,0), colors.white),
        ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
        ("FONTSIZE", (0,0), (-1,-1), 9),
        ("ROWBACKGROUNDS", (0,1), (-1,-1), [CREAM, LIGHT_GOLD]),
        ("GRID", (0,0), (-1,-1), 0.5, GOLD),
        ("TOPPADDING", (0,0), (-1,-1), 3),
        ("BOTTOMPADDING", (0,0), (-1,-1), 3),
    ]))
    return t

def gun_milan_table(gunas, styles):
    headers = ["Kuta", "Score", "Max", "Details"]
    rows = [headers]
    for name, val in gunas.items():
        color_flag = "green" if val["score"] >= val["max"]*0.6 else "red"
        rows.append([name, str(val["score"]), str(val["max"]), val["detail"]])
    t = Table(rows, colWidths=[40*mm, 20*mm, 20*mm, 80*mm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,0), DARK_RED),
        ("TEXTCOLOR", (0,0), (-1,0), colors.white),
        ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
        ("FONTSIZE", (0,0), (-1,-1), 9),
        ("ROWBACKGROUNDS", (0,1), (-1,-1), [CREAM, LIGHT_GOLD]),
        ("GRID", (0,0), (-1,-1), 0.5, GOLD),
        ("TOPPADDING", (0,0), (-1,-1), 3),
        ("BOTTOMPADDING", (0,0), (-1,-1), 3),
    ]))
    return t

# ─── Generate Single Kundli PDF ───────────────────────────────────────────────
def generate_kundli_pdf(kundli_data):
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4,
                            topMargin=25*mm, bottomMargin=18*mm,
                            leftMargin=15*mm, rightMargin=15*mm)
    styles = make_styles()
    story = []

    # Title
    story.append(Spacer(1, 5*mm))
    story.append(Paragraph("॥ श्री गणेशाय नमः ॥", styles["Sanskrit"]))
    story.append(Paragraph("VEDIC BIRTH HOROSCOPE (KUNDLI)", styles["Title1"]))
    story.append(Paragraph(kundli_data["name"], styles["Title2"]))
    story.append(HRFlowable(width="100%", thickness=2, color=GOLD))
    story.append(Spacer(1, 4*mm))

    # Birth Details
    story.append(Paragraph("BIRTH DETAILS", styles["SectionHead"]))
    info = [
        ("Name", kundli_data["name"]),
        ("Gender", kundli_data["gender"]),
        ("Date of Birth", kundli_data["dob"]),
        ("Time of Birth", kundli_data["tob"]),
        ("Latitude", f"{kundli_data['lat']}° N"),
        ("Longitude", f"{kundli_data['lon']}° E"),
        ("Time Zone", f"UTC +{kundli_data['tz_offset']}"),
        ("Julian Day", f"{kundli_data['jd']:.4f}"),
    ]
    story.append(make_info_table(info, styles))
    story.append(Spacer(1, 4*mm))

    # Lagna & Moon
    story.append(Paragraph("LAGNA & MOON SIGN", styles["SectionHead"]))
    lagna = kundli_data["lagna"]
    info2 = [
        ("Lagna (Ascendant)", lagna["rashi"]),
        ("Lagna Degree", f"{lagna['degree']:.2f}°"),
        ("Lagna Lord", lagna["lord"]),
        ("Moon Sign (Rashi)", kundli_data["moon_sign"]),
        ("Nakshatra", kundli_data["nakshatra"]),
        ("Nakshatra Pada", str(kundli_data["nakshatra_pada"])),
        ("Nakshatra Lord", kundli_data["nakshatra_lord"]),
        ("Current Dasha", kundli_data["current_dasha"]),
    ]
    story.append(make_info_table(info2, styles))
    story.append(Spacer(1, 4*mm))

    # Chart
    story.append(Paragraph("BIRTH CHART (NORTH INDIAN STYLE)", styles["SectionHead"]))
    chart = north_indian_chart_svg(kundli_data["houses"], kundli_data["planets"])
    story.append(chart)
    story.append(Spacer(1, 4*mm))

    # Panchang
    story.append(Paragraph("PANCHANG", styles["SectionHead"]))
    p = kundli_data["panchang"]
    info3 = [
        ("Tithi", p["tithi"]),
        ("Vara (Day)", p["vara"]),
        ("Nakshatra", p["nakshatra"]),
        ("Yoga", p["yoga"]),
        ("Karana", p["karana"]),
        ("", ""),
    ]
    story.append(make_info_table(info3, styles))
    story.append(Spacer(1, 4*mm))

    # Planets
    story.append(Paragraph("PLANETARY POSITIONS", styles["SectionHead"]))
    story.append(planet_table(kundli_data["planets"], styles))
    story.append(Spacer(1, 4*mm))

    # Dasha
    story.append(Paragraph("VIMSHOTTARI DASHA", styles["SectionHead"]))
    story.append(dasha_table(kundli_data["dashas"], styles))
    story.append(Spacer(1, 4*mm))

    # Manglik
    story.append(Paragraph("MANGLIK STATUS", styles["SectionHead"]))
    m = kundli_data["manglik"]
    m_color = "red" if m["is_manglik"] else "green"
    story.append(Paragraph(
        f'<font color="{m_color}"><b>{m["note"]}</b></font> — Mars in House {m["mars_house"]}',
        styles["Normal1"]))
    if m["is_manglik"]:
        story.append(Paragraph(
            "Manglik Dosha is present. This can be neutralized if both partners are Manglik, "
            "or through specific puja remedies.", styles["Normal1"]))
    story.append(Spacer(1, 4*mm))

    # Doshas
    story.append(Paragraph("DOSHA ANALYSIS", styles["SectionHead"]))
    dosha_rows = [["Dosha", "Status"]]
    for d_name, d_status in kundli_data["doshas"].items():
        dosha_rows.append([d_name, d_status])
    dt = Table(dosha_rows, colWidths=[90*mm, 90*mm])
    dt.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,0), DARK_RED),
        ("TEXTCOLOR", (0,0), (-1,0), colors.white),
        ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
        ("FONTSIZE", (0,0), (-1,-1), 9),
        ("ROWBACKGROUNDS", (0,1), (-1,-1), [CREAM, LIGHT_GOLD]),
        ("GRID", (0,0), (-1,-1), 0.5, GOLD),
        ("TOPPADDING", (0,0), (-1,-1), 3),
        ("BOTTOMPADDING", (0,0), (-1,-1), 3),
    ]))
    story.append(dt)
    story.append(Spacer(1, 4*mm))

    # Footer note
    story.append(HRFlowable(width="100%", thickness=1, color=GOLD))
    story.append(Paragraph(
        "This Kundli is generated using Lahiri Ayanamsha and Whole-Sign House system. "
        "Planetary positions are approximate. Please consult a qualified Jyotishi for detailed analysis.",
        styles["Small"]))

    doc.build(story, onFirstPage=header_footer, onLaterPages=header_footer)
    buf.seek(0)
    return buf.read()

# ─── Generate Marriage Matching PDF ───────────────────────────────────────────
def generate_matching_pdf(k1, k2, gun_result):
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4,
                            topMargin=25*mm, bottomMargin=18*mm,
                            leftMargin=15*mm, rightMargin=15*mm)
    styles = make_styles()
    story = []

    story.append(Spacer(1, 5*mm))
    story.append(Paragraph("॥ श्री गणेशाय नमः ॥", styles["Sanskrit"]))
    story.append(Paragraph("MARRIAGE COMPATIBILITY REPORT", styles["Title1"]))
    story.append(Paragraph(f"{k1['name']}  &  {k2['name']}", styles["Title2"]))
    story.append(HRFlowable(width="100%", thickness=2, color=GOLD))
    story.append(Spacer(1, 4*mm))

    # Individual details comparison
    story.append(Paragraph("BIRTH DETAILS COMPARISON", styles["SectionHead"]))
    comp_rows = [
        ["Attribute", k1["name"], k2["name"]],
        ["Date of Birth", k1["dob"], k2["dob"]],
        ["Time of Birth", k1["tob"], k2["tob"]],
        ["Lagna", k1["lagna"]["rashi"].split("(")[0], k2["lagna"]["rashi"].split("(")[0]],
        ["Moon Sign", k1["moon_sign"].split("(")[0], k2["moon_sign"].split("(")[0]],
        ["Nakshatra", k1["nakshatra"], k2["nakshatra"]],
        ["Nak. Lord", k1["nakshatra_lord"], k2["nakshatra_lord"]],
        ["Manglik", k1["manglik"]["note"], k2["manglik"]["note"]],
    ]
    ct = Table(comp_rows, colWidths=[50*mm, 65*mm, 65*mm])
    ct.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,0), DARK_RED),
        ("TEXTCOLOR", (0,0), (-1,0), colors.white),
        ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
        ("FONTNAME", (0,0), (0,-1), "Helvetica-Bold"),
        ("FONTSIZE", (0,0), (-1,-1), 9),
        ("ROWBACKGROUNDS", (0,1), (-1,-1), [CREAM, LIGHT_GOLD]),
        ("GRID", (0,0), (-1,-1), 0.5, GOLD),
        ("TOPPADDING", (0,0), (-1,-1), 3),
        ("BOTTOMPADDING", (0,0), (-1,-1), 3),
    ]))
    story.append(ct)
    story.append(Spacer(1, 4*mm))

    # 36 Gun Score
    story.append(Paragraph("36 GUN MILAN (ASHTAKOOT)", styles["SectionHead"]))
    story.append(gun_milan_table(gun_result["gunas"], styles))
    story.append(Spacer(1, 3*mm))

    total = gun_result["total"]
    pct = gun_result["percentage"]
    verdict = gun_result["verdict"]
    v_color = "green" if total >= 24 else ("orange" if total >= 18 else "red")
    story.append(Paragraph(
        f'<b>Total Score: <font color="{v_color}">{total}/36</font>  |  '
        f'Compatibility: <font color="{v_color}">{pct}%  —  {verdict}</font></b>',
        styles["Normal1"]))
    story.append(Spacer(1, 4*mm))

    # Manglik comparison
    story.append(Paragraph("MANGLIK ANALYSIS", styles["SectionHead"]))
    m1 = k1["manglik"]
    m2 = k2["manglik"]
    if m1["is_manglik"] and m2["is_manglik"]:
        m_msg = "Both partners are Manglik. The dosha cancels out. This is considered auspicious."
        m_col = "green"
    elif m1["is_manglik"] or m2["is_manglik"]:
        m_msg = "One partner is Manglik. Remedies like Kumbh Vivah or specific pujas are recommended before marriage."
        m_col = "orange"
    else:
        m_msg = "Neither partner is Manglik. No Manglik Dosha concerns."
        m_col = "green"
    story.append(Paragraph(f'<font color="{m_col}">{m_msg}</font>', styles["Normal1"]))
    story.append(Spacer(1, 4*mm))

    # Nadi & Bhakoot
    story.append(Paragraph("KEY DOSHA SUMMARY", styles["SectionHead"]))
    dosha_info = [
        ["Dosha", "Status", "Remedy"],
        ["Nadi Dosha", "Present" if gun_result["nadi_dosha"] else "Absent",
         "Maha Mrityunjaya Japa" if gun_result["nadi_dosha"] else "None required"],
        ["Bhakoot Dosha", "Present" if gun_result["bhakoot_dosha"] else "Absent",
         "Venus worship, Lakshmi puja" if gun_result["bhakoot_dosha"] else "None required"],
        ["Manglik Dosha", "Both Manglik" if (m1["is_manglik"] and m2["is_manglik"]) else
                         ("One Manglik" if (m1["is_manglik"] or m2["is_manglik"]) else "None"),
         "Dosha cancelled" if (m1["is_manglik"] and m2["is_manglik"]) else
         ("Kumbh Vivah" if (m1["is_manglik"] or m2["is_manglik"]) else "None required")],
    ]
    dst = Table(dosha_info, colWidths=[55*mm, 45*mm, 80*mm])
    dst.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,0), DARK_RED),
        ("TEXTCOLOR", (0,0), (-1,0), colors.white),
        ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
        ("FONTSIZE", (0,0), (-1,-1), 9),
        ("ROWBACKGROUNDS", (0,1), (-1,-1), [CREAM, LIGHT_GOLD]),
        ("GRID", (0,0), (-1,-1), 0.5, GOLD),
        ("TOPPADDING", (0,0), (-1,-1), 3),
        ("BOTTOMPADDING", (0,0), (-1,-1), 3),
    ]))
    story.append(dst)
    story.append(Spacer(1, 4*mm))

    # Strengths and cautions
    story.append(Paragraph("STRENGTHS & CAUTION AREAS", styles["SectionHead"]))
    strengths = []
    cautions = []
    for kuta, val in gun_result["gunas"].items():
        ratio = val["score"] / val["max"]
        if ratio >= 0.7:
            strengths.append(f"{kuta} ({val['score']}/{val['max']})")
        elif ratio < 0.4:
            cautions.append(f"{kuta} ({val['score']}/{val['max']})")

    if strengths:
        story.append(Paragraph(f'<font color="green"><b>Strengths:</b></font> {", ".join(strengths)}', styles["Normal1"]))
    if cautions:
        story.append(Paragraph(f'<font color="red"><b>Caution Areas:</b></font> {", ".join(cautions)}', styles["Normal1"]))
    if not cautions:
        story.append(Paragraph('<font color="green">No major caution areas identified.</font>', styles["Normal1"]))
    story.append(Spacer(1, 4*mm))

    # Overall verdict
    story.append(HRFlowable(width="100%", thickness=2, color=GOLD))
    story.append(Spacer(1, 3*mm))
    v_color2 = "green" if total >= 24 else ("orange" if total >= 18 else "red")
    story.append(Paragraph(
        f'<font color="{v_color2}"><b>OVERALL COMPATIBILITY: {verdict} ({total}/36 = {pct}%)</b></font>',
        styles["Title2"]))

    recommendation = {
        "Excellent": "This match is highly auspicious. The couple is likely to enjoy a harmonious, prosperous, and loving marriage.",
        "Very Good": "This is a very compatible match with strong mutual understanding and support.",
        "Good": "This match is generally favorable. Minor differences may exist but can be resolved with communication.",
        "Average": "This match has some compatibility but also notable differences. Counseling recommended.",
        "Poor": "Significant incompatibilities exist. Detailed consultation with an experienced astrologer is strongly advised."
    }
    story.append(Paragraph(recommendation[verdict], styles["Normal1"]))
    story.append(Spacer(1, 3*mm))
    story.append(HRFlowable(width="100%", thickness=1, color=GOLD))
    story.append(Paragraph(
        "This report is based on Vedic Ashtakoot Gun Milan system. "
        "Consult a qualified Jyotishi for detailed personalized guidance.",
        styles["Small"]))

    doc.build(story, onFirstPage=header_footer, onLaterPages=header_footer)
    buf.seek(0)
    return buf.read()
